export const services = [
  { title: 'Web Design', desc: 'Custom, premium typography and aesthetic grid structures.' },
  { title: 'Frontend', desc: 'Vibrant, high-performance React layouts with fluid animations.' },
  { title: 'Backend', desc: 'Robust server routing, API logic, and scalable architectures.' },
  { title: 'Full-Stack Development', desc: 'End-to-end web deployment linking databases and client applications.' },
  { title: 'Systems Architecture', desc: 'Secure database setups, DNS config, and reverse proxies.' },
  { title: 'Landing Pages', desc: 'Highly optimized page-speed configurations and layouts.' },
  { title: 'Payment Gateway', desc: 'Integration of East African gateways (Pesapal, M-Pesa, Instasend).' },
  { title: 'SEO', desc: 'Structuring search indexing parameters and core vitals audits.' },
  { title: 'Security', desc: 'Supabase Row-Level Security rules and user authorization setups.' },
  { title: 'AI Automations', desc: 'Timed scrapers, Groq/Claude integrations, and telegram alerts.' },
  { title: 'Prompt Engineering', desc: 'Optimizing context structures and workflow system parameters.' },
  { title: 'Consultancy', desc: 'Technical guidance, infrastructure debugging, and design scoping.' },
  { title: 'AI Learning & Training', desc: 'Guiding organizations on AI integration and agent skills.' },
];

export const projects = [
  {
    num: '01',
    title: 'Fareast Ventures',
    role: 'Systems Developer',
    desc: 'Premium Nairobi chauffeur platform featuring automated booking pipelines, real-time emails, Instasend payments routing, and comprehensive SEO performance tuning.',
    tags: ['React', 'Tailwind CSS', 'Instasend', 'SEO Audit'],
    website: 'https://fareastventures.co.ke',
    screenshot: '/fareast_screenshot.png',
    featured: true,
  },
  {
    num: '02',
    title: 'Churnager',
    role: 'Full-Stack Developer',
    desc: 'Customer retention dashboard with Docker Compose orchestration across four services and integrated M-Pesa Daraja STK Push payments.',
    tags: ['TypeScript', 'Python', 'M-Pesa Daraja', 'Docker'],
    website: 'https://frontend-six-rho-pjovt4cc0l.vercel.app',
    canvasStyle: 'Signal Lime',
  },
  {
    num: '03',
    title: 'Wren-Os',
    role: 'Systems Developer',
    desc: 'Full CRUD task, project, and content management with atomic drag-between-Kanban activity logging and a pre-generated agent API.',
    tags: ['TypeScript', 'Kanban', 'Activity Logging', 'API'],
    website: 'https://wren-os-henna-six.vercel.app',
    canvasStyle: 'Chrome Gold',
  },
  {
    num: '04',
    title: 'Shamba Command Center',
    role: 'Full-Stack Developer',
    desc: 'Dual-frontend farm records and inventory command database, comprising a React/Vite dashboard and a Flutter Android app featuring local Google ML Kit text OCR.',
    tags: ['React', 'Flutter', 'Firebase', 'Google ML Kit'],
    repo: 'https://github.com/Glizocksama-2/birunda-farm',
    screenshot: '/invoice_generator.jpg',
  },
  {
    num: '05',
    title: 'GOROSEI',
    role: 'Full-Stack Developer',
    desc: 'Streetwear e-commerce storefront. Replaced hardcoded authorization parameters with secure Supabase Auth and strict Row-Level Security database controls.',
    tags: ['React', 'Supabase Auth', 'Row-Level Security', 'UX Design'],
    website: 'https://gorosei-kenya.vercel.app',
    canvasStyle: 'Matte Black',
  },
  {
    num: '06',
    title: 'LifeRPG',
    role: 'Developer',
    desc: 'Single-file gamified habit tracker PWA with SVG avatar layering, mood logs, and an AI coach proxy routing keys via Netlify serverless functions.',
    tags: ['React PWA', 'Netlify Functions', 'Groq API', 'Local Storage'],
    repo: 'https://github.com/Glizocksama-2/rpgstats',
    canvasStyle: 'Glassmorphism',
  },
  {
    num: '07',
    title: 'Kenyan Tax Intelligence',
    role: 'Full-Stack Developer',
    desc: 'PAYE, NSSF, and NHIF calculator with industry selection shortcuts, standard vs advanced modes, and Supabase persistence.',
    tags: ['TypeScript', 'Supabase', 'PAYE/NSSF/NHIF', 'Vercel'],
    website: 'https://kenyan-tax-intelligence.vercel.app',
    canvasStyle: 'Industrial Red',
  },
  {
    num: '08',
    title: 'Water & Sanitation NPO',
    role: 'Full-Stack Developer',
    desc: 'Six-page donor coordination hub accepting international USD cards settled to local banks via Pesapal API, with automated Resend transactional alerts.',
    tags: ['HTML/CSS', 'Pesapal API', 'Resend', 'AI Help Widget'],
    canvasStyle: 'Fluid Aqua',
  },
  {
    num: '09',
    title: 'EStarz FC',
    role: 'Mobile Developer',
    desc: 'Android application for sports club tracking, integrating user registrations, validation, and structured WhatsApp sales pipelines.',
    tags: ['Kotlin', 'Material Design', 'Android SDK', 'Input Validation'],
    repo: 'https://github.com/Glizocksama-2/EStarzFc',
    canvasStyle: 'Sport Royal',
  },
  {
    num: '10',
    title: 'Saka Wera',
    role: 'Workflow Automator',
    desc: 'Automated job application matching engine powered by n8n. Scrapes major local boards, processes relevancy with Groq LLM filters, and fires alerts to Telegram.',
    tags: ['n8n', 'Groq AI', 'Telegram API', 'Automation'],
    repo: 'https://github.com/Glizocksama-2/Saka-Wera',
    canvasStyle: 'Urban Amber',
  },
];

export const techStacks = [
  { group: 'Frontend', items: ['React', 'Vite', 'HTML5', 'CSS3', 'Tailwind CSS', 'Framer Motion'] },
  { group: 'Backend', items: ['Node.js', 'Express', 'n8n pipelines', 'PostgreSQL', 'Supabase'] },
  { group: 'Mobile', items: ['Kotlin', 'Android SDK', 'Flutter', 'Method Channels'] },
  { group: 'AI & Automation', items: ['Groq API', 'Claude API', 'Telegram Bot API', 'System Scraping'] },
  { group: 'Infrastructure', items: ['Docker', 'Docker Compose', 'Render', 'Netlify', 'Nginx', 'DNS Setup'] },
  { group: 'Payments', items: ['Pesapal Routing', 'Instasend API', 'M-Pesa Integrations'] },
];

export const certificates = [
  'Claude 101', 'Claude Code 101', 'Claude Platform 101', 'Introduction to Claude Cowork',
  'Claude Code in Action', 'AI Fluency: Framework and Foundations', 'Building with Claude API',
  'Introduction to Model Context Protocol', 'AI Fluency for Educators', 'AI Fluency for Students',
  'Model Context Protocol: Advanced Topics', 'Claude with Amazon Bedrock', 'Claude with Google Cloud Vertex AI',
  'Teaching AI Fluency', 'AI Fluency for Non Profits', 'Introduction to Agent Skills',
  'Introduction to Subagents', 'AI Capabilities and Limitations', 'AI Fluency for Small Businesses',
  'AI Fluency for Builders',
];

export const contact = {
  email: 'brianmukwe097@gmail.com',
  phone: '+254 792 300 552',
  phoneRaw: '254792300552',
  location: 'Nairobi, Kenya — GMT+3',
  whatsapp: (message) => `https://wa.me/254792300552?text=${encodeURIComponent(message)}`,
};
